filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: "-service"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json.keys_under_root: true
              json.add_error_key: true
              json.message_key: message
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"
                - decode_json_fields:
                    fields: ["log"]
                    target: ""
                    overwrite_keys: true

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  indices:
    - index: "aquarium-logs-%{+yyyy.MM.dd}"
      when.contains:
        container.name: "-service"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
