package it.f3rren.aquarium.aquariums_service.model;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Aquarium entity representing an aquarium in the system.
 * This class maps to the 'aquariums' table in the database.
 * It includes fields for the aquarium's ID, name, volume, type, creation timestamp, description, and image URL.
 * @author F3rren
 */
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Table(name = "aquariums")
public class Aquarium {

    /**
     * Unique identifier for the aquarium.
     * Automatically generated by Hibernate.
     * @Id annotation marks this field as the primary key.
     * @GeneratedValue annotation specifies the generation strategy for the ID.
     * @Column annotation defines the column name in the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * Name of the aquarium.
     * Must be provided when creating a new aquarium.
     * @NotNull annotation ensures that the name is not null.
     * @Size Must be between 2 and 100 characters.
     * @Column annotation defines the column name in the database.
     */
    @NotNull
    @Size(min = 2, max = 100)
    @Column(name = "name")
    private String name;

    /**
     * Volume of the aquarium in liters.
     * Must be positive and non-zero.
     * @NotNull annotation ensures that the volume is not null.
     * @Min annotation ensures that the volume is at least 1.
     * @Column annotation defines the column name in the database.
     */
    @NotNull
    @Min(1)
    @Column(name = "volume")
    private int volume;

    /**
     * Type of the aquarium.
     * Can be "saltwater" or "freshwater".
     * @NotNull annotation ensures that the volume is not null.
     * @Size Must be between 2 and 50 characters.
     * @Column annotation defines the column name in the database.
     */
    @NotNull
    @Size(min = 2, max = 50)
    @Column(name = "type")
    private String type;

    /**
     * Creation timestamp of the aquarium.
     * Automatically set when the aquarium is created.
     * @CreationTimestamp annotation specifies that this field is automatically set to the current timestamp when the entity is created.
     * @Column annotation defines the column name in the database.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Description of the aquarium.
     * Can be used to provide additional information about the aquarium.
     * @Size annotation ensures that the description is not more than 500 characters.
     * @Column annotation defines the column name in the database.
     */
    @Size(max = 500)
    @Column(name = "description")
    private String description;

    /**
     * URL of the image associated with the aquarium.
     * Can be used to display a visual representation of the aquarium.
     * @Size annotation ensures that the description is not more than 2000 characters.
     * @Column annotation defines the column name in the database.
     */
    @Size(max = 2000)
    @Column(name = "image_url")
    private String imageUrl;

    /**
     * Constructor for Aquarium.
     * Initializes the aquarium with a name and volume.
     * @param name Name of the aquarium.
     * @param volume Volume of the aquarium in liters.
     */
    public Aquarium(String name, int volume) {
        this.name = name;
        this.volume = volume;
    }

}