package it.f3rren.aquarium.aquariums_service.model;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.*;
import lombok.*;

/**
 * Aquarium entity representing an aquarium in the system.
 * This class maps to the 'aquariums' table in the database.
 * It includes fields for the aquarium's ID, name, volume, type, creation timestamp, description, and image URL.
 * @author F3rren
 */
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Table(name = "aquariums")
public class Aquarium {

    /**
     * Unique identifier for the aquarium.
     * Automatically generated by Hibernate.
     * @Id annotation marks this field as the primary key.
     * @GeneratedValue annotation specifies the generation strategy for the ID.
     * @Column annotation defines the column name in the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * Name of the aquarium.
     * Must be provided when creating a new aquarium.
     * @Column annotation defines the column name in the database.
     */
    @Column(name = "name")
    private String name;

    /**
     * Volume of the aquarium in liters.
     * Must be positive and non-zero.
     * @Column annotation defines the column name in the database.
     */
    @Column(name = "volume")
    private int volume;

    /**
     * Type of the aquarium.
     * Can be "saltwater" or "freshwater".
     * @Column annotation defines the column name in the database.
     */
    @Column(name = "type")
    private String type;

    /**
     * Creation timestamp of the aquarium.
     * Automatically set when the aquarium is created.
     * @CreationTimestamp annotation specifies that this field is automatically set to the current timestamp when the entity is created.
     * @Column annotation defines the column name in the database.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Description of the aquarium.
     * Can be used to provide additional information about the aquarium.
     * @Column annotation defines the column name in the database.
     */
    @Column(name = "description")
    private String description;

    /**
     * URL of the image associated with the aquarium.
     * Can be used to display a visual representation of the aquarium.
     * @Column annotation defines the column name in the database.
     */
    @Column(name = "image_url")
    private String imageUrl;

    /**
     * Constructor for Aquarium.
     * Initializes the aquarium with a name and volume.
     * @param name Name of the aquarium.
     * @param volume Volume of the aquarium in liters.
     */
    public Aquarium(String name, int volume) {
        this.name = name;
        this.volume = volume;
    }

}