package it.f3rren.aquarium.aquariums_service.dto;

import java.time.LocalDateTime;
import lombok.*;
/**
 * DTO for water parameter data transfer.
 * Represents a water parameter measurement for an aquarium.
 * @author F3rren
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class WaterParameterDTO {

    /**
     * Water parameter ID.
     * This is the unique identifier for the water parameter measurement.
     * This field is optional because it will be automatically generated by the system.
     */
    private Long id;

    /**
     * Aquarium ID.
     * This is the unique identifier for the aquarium that the water parameter measurement belongs to.
     * This field is required for the creation of a water parameter measurement.
     * It is used to associate the water parameter measurement with a specific aquarium.
     */
    private Long aquariumId;

    /**
     * Temperature measurement.
     * Represents the temperature of the aquarium water in degrees Celsius.
     * This field is required for the creation of a water parameter measurement.
     */
    private Double temperature;

    /**
     * pH measurement.
     * Represents the pH level of the aquarium water.
     * This field is optional because pH levels can be variable.
     */
    private Double ph;

    /**
     * Salinity measurement.
     * Represents the amount of salt  in the aquarium water.
     * This is a measurement in milligrams per liter (mg/L).
     * This field is optional because salt levels can be variable.
     */
    private Double salinity;

    /**
     * Measurement timestamp.
     * Represents the date and time when the water parameter measurement was taken.
     * This field is required for the creation of a water parameter measurement.
     */
    private LocalDateTime measuredAt;
}
