spring.application.name=target_parameter-service
server.port=8087

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aquarium_ms}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=parameters

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=parameters
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.table=flyway_schema_history_target

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

# Error handling
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.it.f3rren.aquarium=INFO
logging.level.org.springframework.web=INFO
